---
- hosts: all
  become: yes
  pre_tasks:
    - name: "install etckeeper"
      apt: name=etckeeper
  roles:
    - znzj.ja_jp
    - packages
    - znz.journald
  vars_files:
    - config.yml
- hosts: all
  become: no
  roles:
    - znz.user-dot-shell
    - znz.user-vim
    - terraform
  vars_files:
    - user-config.yml
