---
- name: enable auto updates
  debconf:
    name: unattended-upgrades
    question: unattended-upgrades/enable_auto_updates
    vtype: boolean
    value: "true"
- name: install unattended-upgrades
  apt: name=unattended-upgrades
- name: setup Unattended-Upgrade::Remove-Unused-Dependencies
  lineinfile:
    dest: "/etc/apt/apt.conf.d/50unattended-upgrades"
    regexp: '//(Unattended-Upgrade::Remove-Unused-Dependencies ")false(";)'
    line: '\1true\2'
    backrefs: yes
